apiVersion: v1
kind: Service
metadata:
  name: k8s-web-hello
spec:
  type: LoadBalancer
  selector:
    app: k8s-web-hello # the same as matchLabels on web-hello-deployment.yaml file
  ports:
  - port: 3000
    targetPort: 3000 # container exposed port
