apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx # must be the same as matchLabels
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx  # must be the same as expected in index.mjs file
spec:
  selector:
    app: nginx # the same as the matchLabels in the Deployment config
  ports:
  - port: 80 # will be same to targetPort
